yatube/about/urls.py
from . import views
from django.urls import path


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index',),
    # Группы постов
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Новая запись
    path('create/', views.post_create, name='post_create'),
    # Редактирование записи
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Комментарий
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    # Подписка
    path('follow/', views.follow_index, name='follow_index'),    
    path(
        'profile/<str:username>/follow/',
        views.profile_follow, name='profile_follow',
    ),
    # Отписка
    path('profile/<str:username>/unfollow/',
    views.profile_unfollow, name='profile_unfollow'
    ),
]

yatube/users/urls.py
from . import views
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'justpage/',
        views.JustStaticPage.as_view()
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'reset/<uid64>/<token>',
        PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(),
        name='password_reset_done'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">
      <p>
        © {{ year }} Copyright
        <span style="color:red">Ya</span>tube
      </p> 
    </div>    
</footer>

yatube/templates/includes/header.html
{% load static %}


<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'about:author' %}
        active
        {% endif %}"
         href="{% url 'about:author' %}">
         Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}
        active
        {% endif %}"
         href="{% url 'about:tech' %}">
         Технологии</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:password_change_form' %}">Изменить пароль</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-dark" href="{% url 'posts:profile' user.username %}"> Пользователь: {{ user.username }}</a>
      </li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:login' %}
        active
        {% endif %}"
         href="{% url 'users:login' %}">
         Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:signup' %}
        active
        {% endif %}"
         href="{% url 'users:signup' %}">
         Регистрация</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endwith %}