yatube/about/urls.py
from . import views
from django.urls import path


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index',),
    # Группы постов
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Новая запись
    path('create/', views.post_create, name='post_create'),
    # Редактирование записи
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Комментарий
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    # Подписка
    path('follow/', views.follow_index, name='follow_index'),    
    path(
        'profile/<str:username>/follow/',
        views.profile_follow, name='profile_follow',
    ),
    # Отписка
    path('profile/<str:username>/unfollow/',
    views.profile_unfollow, name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Post(models.Model):
    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    pub_date = models.DateTimeField(
        'Дата создания',
        auto_now_add=True,
        db_index=True
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):

    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите комментарий',
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.user} --> {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .utils import paginate_page
from .models import Follow, Post, Group, User, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required


def index(request):
    post_list = Post.objects.select_related("group", "author")
    page_obj = paginate_page(request, post_list)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related("author", "group")
    page_obj = paginate_page(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    page_obj = paginate_page(request, posts)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user.id,
            author=author.id
        ).exists()
    else:
        following = False
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=post)
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    is_edit = False
    context = {'form': form, 'is_edit': is_edit}
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user)
    form = PostForm()
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None
    )
    context = {'form': form, 'is_edit': is_edit, 'post': post}
    if request.method == 'POST':
        if form.is_valid():
            post = form.save()
            return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

@login_required
def follow_index(request):
    post = Post.objects.filter(author__following__user=request.user)
    page_obj = paginate_page(request, post)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)

@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)
    
@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(
        user=request.user,
        author=author
    ).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
<title>
{% if is_edit %}
Редактировать пост
{% else %}
Новый пост
{% endif %}
</title>
{% endblock title %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}   
                Редактировать запись
                {% else %}  
                Новая запись         
                {% endif %}    
              </div>
              <div class="card-body">      
                {% if is_edit %}  
                <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_id=post.id %}">
                {% else %}   
                <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create'%}">
                {% endif %}
                {% csrf_token %}

                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.text }}  
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    {{ form.group }}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create'%}">
                    <label for="id_image">
                      Картинка                      
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                            
                     <div class="form-group row my-3 p-3">            
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                      Сохранить
                      {% else %}
                      Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}<title>Ваши подписки</title>{% endblock %}
{% block content %}
<div class="container py-5">
<h1>Подписки</h1>
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/post_list.html' %}
  <ul>
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
    {% endif %}
  </ul>
  <ul>
    <a class="btn btn-primary" href="{% url 'posts:post_detail' post.pk %}">
      Подробная информация
    </a>
  </ul>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
<title>Записи сообщества{{ slug }}</title>
{% endblock title %}

{% block content %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
<div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>      
    <p>
      {{ post.text }}
    </p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</div>   
{% endblock content%}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}<title>Последние обновления на сайте</title>{% endblock %}
{% block content %}
<div class="container py-5">
<h1>Последние обновления на сайте</h1>
{% include 'posts/includes/switcher.html' %}
{% cache 20 index_page page_obj %}
  {% for post in page_obj %}
    {% include 'posts/includes/post_list.html' %}
  <ul>
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
    {% endif %}
  </ul>
  <ul>
    <a class="btn btn-primary" href="{% url 'posts:post_detail' post.pk %}">
      Подробная информация
    </a>
  </ul>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}


{% block title %}
 <title>{{ post|truncatechars:30 }}</title>
{% endblock title %}
{% block content %}
<div class="container py-5">
  Дата публикации: {{ post.pub_date|date:"d E Y" }}  
   <li class="list-group-item">
      Группа: {{ post.group.title }}
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">
    все записи группы
    </a>
  {% endif %}
    </li>
    <li class="list-group-item">
    Автор: {{ post.author.get_full_name }}
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
    Всего постов автора:  {{ post.author.posts.count }}
    </li>
    <li class="list-group-item">
    <a href="{% url 'posts:profile' post.author %}">
    все посты пользователя
    </a>
    </li>
    </ul>
    {% thumbnail post.image "960x339" upscale=True as im %}
    <img class="fit-picture" src="{{ im.url }}">
    {% endthumbnail %}
    <article class="col-12 col-md-9">
    <p>
      {{ post.text|linebreaksbr }} 
    </p>
    </article>
    {% if user == post.author %}
    <a href="{% url 'posts:post_edit' post.pk %}">
      Редактировать запись
    </a>
    {% endif %}
    {% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author %}">
          {{ comment.author }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
        <h6>
        {{ comment.created|date }}
        </h6>
      </p>
    </div>
  </div>
{% endfor %}
</div>
{% if user.is_authenticated %}
  <div class="container">
    <h5 class="container">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

    <!-- Подключены иконки, стили и заполенены мета теги -->
{% block title %}
  <title>Это страница пользователя</title>
{% endblock %}
{% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a
              href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
          {{ post.text }}
          </p>
          {% thumbnail post.image "960x339" upscale=True as im %}
            <img class="fit-picture" src="{{ im.url }}">
          {% endthumbnail %}
        <ul>
          <a href="{% url 'posts:post_detail' post.pk %}">
            подробная информация 
          </a>
        </ul>
        </article>   
        {% if post.group %} 
        <ul>   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        </ul>
        {% endif %}      
        <hr>
        {% endfor %}
        <!-- Остальные посты. после последнего нет черты -->
        {% include 'posts/includes/paginator.html' %} 
      </div>
{% endblock content %}